name: Build Binaries

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            arch: x64
            runs_on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.8'
          architecture: ${{ matrix.arch }}

      - name: Build for Linux
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sh scripts/build_linux.sh ${{ matrix.arch }}

      - name: Build for Windows
        if: startsWith(matrix.os, 'windows')
        run: |
          scripts\build_win.bat ${{ matrix.arch }}

      - name: Build for macOS
        if: startsWith(matrix.os, 'macos')
        run: |
          sh scripts/build_macos.sh ${{ matrix.arch }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: digmacro-${{ startsWith(matrix.os, 'ubuntu') && 'linux' || (startsWith(matrix.os, 'windows') && 'windows' || 'macos') }}-${{ matrix.arch }}
          path: output/
